//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MainContentListShowCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainContentListShowCode()
        {
            this.MainContentListTagFather = new HashSet<MainContentListTagFather>();
            this.MainContentListTagSon = new HashSet<MainContentListTagSon>();
        }
    
        public int Id { get; set; }
        [DisplayName("代码")]
        public string Code { get; set; }
        [DisplayName("描述")]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainContentListTagFather> MainContentListTagFather { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainContentListTagSon> MainContentListTagSon { get; set; }
    }
}
