//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MainContentListTagBehavior
    {
        public int Id { get; set; }
        [DisplayName("行为标签名")]
        public string Name { get; set; }
        [DisplayName("内容标签id")]
        public Nullable<int> ContentListTagSonId { get; set; }
        [DisplayName("链接")]
        public string UrlName { get; set; }
        [DisplayName("是否更新")]
        public Nullable<short> IsUpadte { get; set; }
        [DisplayName("是否删除")]
        public Nullable<short> IsDelete { get; set; }
        [DisplayName("创建日期")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
