//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MainContentListTagFather
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainContentListTagFather()
        {
            this.MainContentListTagSon = new HashSet<MainContentListTagSon>();
        }
    
        public int Id { get; set; }
        [DisplayName("模块名称")]
        public string Name { get; set; }
        [DisplayName("所属代码Id")]
        public Nullable<int> ShowCodeId { get; set; }
        [DisplayName("所属内容Id")]
        public Nullable<int> FatherId { get; set; }
        [DisplayName("访问链接")]
        public string UrlName { get; set; }
        [DisplayName("是否更新")]
        public Nullable<short> IsUpadte { get; set; }
        [DisplayName("是否删除")]
        public Nullable<short> IsDelete { get; set; }
        [DisplayName("创建日期")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual MainContentListShowCode MainContentListShowCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainContentListTagSon> MainContentListTagSon { get; set; }
    }
}
